### ISSUE TITLE
Receiver clock file contains epochs with minute=60

### ISSUE THREAD

**Issue by aewallin** [PrideLab/PRIDE-PPPAR#4] opened 2022-04-01 16:45 UTC
I'm seeing results in the receiver clock file "rck" with minute=60, which is not valid as input for e.g. python datetime.

For example:

>  Year   Mon   Day  Hour   Min       Sec
>  2022     2    19     0    59 30.000000 
>  2022     2    19     0    60  0.000000
>  2022     2    19     1     0 30.000000 

The middle line in this example is invalid, and should have minute=0 and hour=1, like this:

> 2022     2    19     1     0  0.000000

**Comment by PrideLab** [comment] 2022-04-07 12:24
Thanks for your feedback, this bug is caused by wrongly carry second to minute but not carry minute to hour in _lsq_rcv_prmt.f90_, and it has been fixed in the newly release version 2.2.

**Closed by PrideLab** 2022-04-07 12:24 UTC
